
use Northwind
---02_Analisis_Clientes.sql


WITH CLIENTE_FRECUENTES_RENTABLES AS(

  SELECT C.CUSTOMERID AS IDCLIENTE,
         C.COMPANYNAME AS CLIENTE,
		 ROUND(SUM(OD.UNITPRICE*OD.QUANTITY*(1-OD.DISCOUNT)),2) AS VENTAS_TOTALES,
		 COUNT(DISTINCT O.ORDERID) AS TOTAL_PEDIDOS
		 FROM ORDERS O INNER JOIN [Order Details] OD
         ON O.OrderID=OD.OrderID
		 INNER JOIN Customers C ON O.CustomerID=C.CustomerID
		 GROUP BY C.CustomerID, C.COMPANYNAME 
		 )

   SELECT TOP 10
       IDCLIENTE,
	      CLIENTE,
		  CONCAT('S/ ',CAST(VENTAS_TOTALES AS VARCHAR(MAX))) AS 'VENTA TOTALES',
		  TOTAL_PEDIDOS 
          FROM CLIENTE_FRECUENTES_RENTABLES
	      ORDER BY VENTAS_TOTALES DESC
  





  