
use Northwind

WITH CLIENTES_PRODUCTOS AS (
select DISTINCT  O.customerID AS CLIENTE , 
       OD.PRODUCTID AS PRODUCTO
		FROM Orders O
		INNER JOIN [Order Details] OD
		ON O.OrderID=OD.OrderID
		) ,

CLIENTES_SIMILARES AS (
 SELECT C1.CLIENTE AS CLIENTEBASE , C2.CLIENTE AS CLIENTE_SIMI,
 COUNT(*) AS PRODUCTO
 FROM CLIENTES_PRODUCTOS C1 INNER JOIN 
 CLIENTES_PRODUCTOS C2 ON C1.PRODUCTO=C2.PRODUCTO AND C1.CLIENTE<>C2.CLIENTE
 GROUP BY C1.CLIENTE , C2.CLIENTE
 HAVING COUNT(*)>=2
),
RECOMENDACIONES AS (

  SELECT CS.CLIENTEBASE ,
         CP.PRODUCTO,
		 COUNT(*) AS FRECUENCIAS
		 FROM CLIENTES_SIMILARES CS
		 INNER JOIN CLIENTES_PRODUCTOS CP
		 ON CS.CLIENTE_SIMI=CP.CLIENTE
		 LEFT JOIN  CLIENTES_PRODUCTOS CP1
		 ON CP1.CLIENTE=CS.CLIENTEBASE
		 AND CP1.PRODUCTO=CP.PRODUCTO
		 WHERE CP1.PRODUCTO IS NULL
		 GROUP BY CS.CLIENTEBASE,CP.PRODUCTO
)

SELECT 
     CLIENTEBASE,
	 PRODUCTO,
	 FRECUENCIAS
	 FROM RECOMENDACIONES
	 ORDER BY CLIENTEBASE,FRECUENCIAS DESC






