

--06_Vistas_Procedimientos.sql

CREATE VIEW TOP10_CLIENTE
AS

SELECT TOP 10 O.CUSTOMERID AS CLIENTE,
   ROUND(SUM(OD.UNITPRICE*OD.QUANTITY*(1-OD.DISCOUNT)),2) AS INGRESO_TOTAL
   FROM Orders O 
   INNER JOIN [Order Details] OD ON O.OrderID=OD.OrderID
   GROUP BY O.CustomerID 
   ORDER BY 2 DESC





